apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  namespace: gic-group-6
spec:
  selector:
    app: mongodb-exporter
  ports:
    - protocol: TCP
      port: 9216
      targetPort: 9216
