version: '3.7'
services:
  api:
    image: thenews_api
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 8000:8000
    restart: always
      
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

volumes:
  mongo: