version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: thenews
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

volumes:
  mongo: