version: '3.7'

services:
  cache:
    image: redis:7.0.9-alpine
    container_name: redis
    restart: always
    env_file:
      - ./.env
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    entrypoint: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} --maxmemory 512mb --maxmemory-policy allkeys-lru