apiVersion: v1
kind: Service
metadata:
  name: sentinel
  namespace: gic-group-6
  labels:
    app: sentinel
spec:
  clusterIP: None
  ports:
    - name: sentinel
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: sentinel