apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config-map
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    dbfilename dump.rdb
    dir /data
    appendonly yes
    appendfilename "appendonly.aof"
    masterauth `5$!DfwSJ.Y(d:@M
    masteruser replication