apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gic-group-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: registry.deti:5000/gic-group-6/frontend:v1  
        resources:
          requests:
            memory: "32Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80