apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: gic-group-6
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: mongodb
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017