apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-secondary
  namespace: gic-group-6
spec:
  serviceName: mongodb
  replicas: 3
  selector:
    matchLabels:
      app: mongodb-secondary
  template:
    metadata: 
      labels:
        app: mongodb-secondary
    spec:
      containers:
        - name: mongodb-secondary
          image: bitnami/mongodb:5.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: mongodb
            - name: MONGODB_REPLICA_SET_MODE
              value: secondary
            - name: MONGODB_INITIAL_PRIMARY_HOST
              value: mongodb-primary
            - name: MONGODB_INITIAL_PRIMARY_PORT_NUMBER
              value: "27017"
            - name: MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD
              value: password123
            - name: MONGODB_REPLICA_SET_KEY
              value: replicasetkey123
          volumeMounts:
            - name: pvc
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: pvc
        namespace: gic-group-6
      spec:
        accessModes:  
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi
