apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-primary
  namespace: gic-group-6
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-primary
  template:
    metadata: 
      labels:
        app: mongodb-primary
    spec:
      containers:
        - name: mongodb-primary
          image: bitnami/mongodb:4.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_ROOT_PASSWORD
              value: password123
            - name: MONGODB_REPLICA_SET_MODE
              value: primary
            - name: MONGODB_REPLICA_SET_KEY
              value: replicasetkey123
          volumeMounts:
            - name: pvc
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: pvc
        namespace: gic-group-6
      spec:
        accessModes:  
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi