apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: gic-group-6
spec:
  serviceName: mongodb
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata: 
      labels:
        app: mongodb
        selector: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.0.17
          ports:
            - containerPort: 27017
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - "rs0"
          volumeMounts:
            - name: pvc
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes:  
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi