apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: gic-group-6
spec:
  serviceName: mongodb
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata: 
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.0.17
          ports:
            - containerPort: 27017
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - "rs0"
          volumeMounts:
            - name: pvc
              mountPath: /data/db
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          type: redis-cluster 
  volumeClaimTemplates:
    - metadata:
        name: pvc
        namespace: gic-group-6
      spec:
        accessModes:  
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi
    
