apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: gic-group-6
  labels:
    app: redis
spec:
  publishNotReadyAddresses: true    # publish endpoints for the Redis Cluster pods even if they are not ready yet
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-cluster