apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config-map
  namespace: gic-group-6
data:
  # update-node-sh -> Updates redis cluster conf. file with IP address of the pod and execute redis proccess (happens when pod is (re)started )
  update-node.sh: |
    #!/bin/sh
    REDIS_NODES="/data/nodes.conf"
    sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_IP}/" ${REDIS_NODES}
    exec "$@"
  # redis.conf -> Stores the configuration arguments for the redis pods
  redis.conf: |+
    bind 0.0.0.0
    port 6379
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no